# Generated by Django 4.2 on 2024-06-25 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snumber', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Номер ящика')),
                ('area', models.FloatField(verbose_name='Площадь')),
                ('dimensions', models.CharField(max_length=255, verbose_name='Размеры')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Ящик',
                'verbose_name_plural': 'Ящики',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало аренды')),
                ('end', models.DateTimeField(verbose_name='Конец аренды')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.box', verbose_name='Ящик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='storage.storage', verbose_name='Склад'),
        ),
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('snumber',)},
        ),
    ]
