# Generated by Django 4.2 on 2024-06-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Необработан'), (2, 'Подтверждена'), (3, 'Отменена'), (4, 'Aрендован'), (5, 'Завершена'), (6, 'Отменена')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало аренды'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/profile', verbose_name='Фото')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', unique=True, verbose_name='телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
