# Generated by Django 4.2 on 2024-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aрендован'), (2, 'Завершена'), (3, 'Просрочена')], default=1, verbose_name='Статус'),
        ),
    ]
