# Generated by Django 4.2 on 2024-06-26 18:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_rent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU', verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile/default.jpg', upload_to='images/profile', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='status',
            field=models.IntegerField(choices=[(1, 'Aрендован'), (2, 'Завершена'), (3, 'Просрочена')], null=True, verbose_name='Статус'),
        ),
    ]
