# Generated by Django 4.2.9 on 2024-06-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_profile_phone_alter_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='address',
        ),
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='storage',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
