# Generated by Django 4.2.9 on 2024-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_storage_address_storage_city_storage_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='from_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='rent',
            name='from_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='box',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
