# Generated by Django 4.2.9 on 2024-06-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_rent_from_city_rent_from_street_rent_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='storage.box', verbose_name='Ящик'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.profile', verbose_name='Пользователь'),
        ),
    ]
