# Generated by Django 4.2.9 on 2024-06-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_rent_box_alter_rent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='profile',
        ),
    ]
