# Generated by Django 4.2.9 on 2024-06-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_advertising'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('email', models.EmailField(max_length=255, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='storage.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
