# Generated by Django 4.2.9 on 2024-06-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_alter_message_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(blank=True, max_length=255, verbose_name='Город')),
                ('from_street', models.CharField(blank=True, max_length=255, verbose_name='Улица')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Доставка')),
                ('start_rent', models.DateTimeField(verbose_name='Начало аренды')),
                ('end_rent', models.DateTimeField(verbose_name='Конец аренды')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storage.box', verbose_name='Ящик')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at', 'updated_at'],
            },
        ),
    ]
