# Generated by Django 4.2.9 on 2024-06-30 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_order_url_confirmation_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='url_confirmation',
        ),
        migrations.AddField(
            model_name='order',
            name='uidb64',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
