# Generated by Django 4.2.9 on 2024-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_remove_order_url_confirmation_order_uidb64'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='url_confirmation',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка подтверждения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uidb64',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
