# Generated by Django 4.2.9 on 2024-07-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_order_url_confirmation_alter_order_uidb64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='from_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='from_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start',
            field=models.DateTimeField(verbose_name='Начало аренды'),
        ),
    ]
