# Generated by Django 5.0.6 on 2024-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_rent_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='partial',
            field=models.BooleanField(default=False, verbose_name='Частичный забор вещей'),
        ),
    ]
